name: Build Campusxchange Backend
on:
  push:
    paths:
      - "campusxchange/**"
    branches: ["develop","main"]
  pull_request:
    paths:
      - "campusxchange/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-campusxchange-api:
    name: Build Campusxchange api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./campusxchange
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run : |
          echo "Building Docker Image with Jib..."
          ./mvnw clean compile jib:build -Dimage=${{ secrets.DOCKERHUB_USERNAME }}/campusxchange-api:${{ github.sha }}
          echo "Pushing the image to Docker Hub..."
          echo "Done!"

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          echo "Setting up kubeconfig for EKS cluster..."
          aws eks update-kubeconfig --region us-east-1 --name test-cluster
          echo "kubeconfig set up successfully."

      - name: Deploy to EKS
        run: |
          echo "Updating Kubernetes Deployment..."
          kubectl set image deployment/campusxchange-api-deployment campusxchange-api=${{ secrets.DOCKERHUB_USERNAME }}/campusxchange-api:${{ github.sha }}
          echo "Deployment updated successfully!"
