name: Build Campusxchange UI

on:
  push:
    paths:
      - "campusxchange-ui/**"
    branches: ["develop"]
  pull_request:
    paths:
      - "campusxchange-ui/**"
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build-campusxchange-ui:
    name: Build Campusxchange-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./campusxchange-ui
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: campusxchange-ui/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run : |
          echo "Pushing the image to Docker Hub..."

      - name: Build and Publish Docker Image
        run: |
          echo "Building Frontend Docker Image..."
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/campusxchange-ui:${{ github.sha }} .
          echo "Pushing Docker Image to Docker Hub..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/campusxchange-ui:${{ github.sha }}
          echo "****Done!***"

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          echo "Setting up kubeconfig for EKS cluster..."
          aws eks update-kubeconfig --region us-east-1 --name test-cluster
          echo "kubeconfig set up successfully."

      - name: Deploy to EKS
        run: |
          echo "Updating Kubernetes Deployment..."
          kubectl set image deployment/campusxchange-ui-deployment campusxchange-ui=${{ secrets.DOCKERHUB_USERNAME }}/campusxchange-ui:${{ github.sha }}
          echo "Deployment updated successfully!"
